### ISSUE TITLE
Problem with stop_thread()

### ISSUE THREAD

**Issue by Jennifer92** [th0ma5w/rtl_fm_python#5]
First of all, thanks for your code in Python. It has been very useful for me.
I have a problem for finishing the rtl_fm command. I want to store audio for a frequency and after, stop this record and start another one with a different frequency.  For this reason, I need stop rtl_fm and start again, because it is not enough setting a new frequency, I have to finish this process and start a new process for collecting audio in a new file.
When I use rtl_fm_finish(), I can stop the process totally and whe I open another one I recive this error:
Please specify a frequency.
usb_claim_interface error -6
Failed to open rtlsdr device #0.

When I use rtl_finish(), the process seems finishished but If I don't interrupt my web service with the keyboard, my rtl is bussy:
Using device 0: Generic RTL2832U OEM
usb_claim_interface error -6
Failed to open rtlsdr device #0.

Could you help me with this problem? Have you seen anything similar?
I am not sure if it is a problem of rtl_fm.c.

**Comment by th0ma5w** [comment]
Heya, first off, thank you so much for posting an issue about this as I believe I've experienced this myself at some point.

I'm not in a position to test this at the moment, but I did want to describe what I personally think is going on, and you're definitely on the right track I think. I believe that the process is leaving threads hanging, or otherwise leaving the file pointer to the USB device open, and this is perhaps a per-process thing and not a per-thread thing... and now that I look at the code, it seems that this is because a lot of threads are created in rtl_fm.c and my stop functions aren't enough to find all of the threads and open pointers and close them such that they are ready to be re-opened. This is all done automatically though when the parent process finishes.

 So, I'll try messing around with this here soon. There could be a way to do what you want however using something like "subprocess" or perhaps even "multiprocessing," the latter of which may be at least to me the most confusing to orchestrate. But with Subprocess, you could simply skip all of my code and just use the rtl_fm binary directly to write out your files... just use your web app to shell out to a command line that includes rtl_fm the real normal way, and then it'll close all on its own normally, and furthermore clean up after itself automatically. 

I'd be curious too as to if the above works, or also if you have other requirements you think necessitate this project with what you're trying to do. I also sincerely appreciate your time in reaching out. I'll also try playing around to see if I can get full closing of all the things that get opened as that would indeed be a very nice ability for the project.

**Comment by Jennifer92** [comment]
Thanks for your quick answer. I appreciate your interest.
In fact, I'm using subprocess in my project in this way:
    argu_input=['-d','0','-M','wbfm','-f','99.5M','-g', '40','-p', '60', '-s','300000','s15']
    rtl_fm_python_thread.make_rtl_fm_thread(args=argu_input) 
    rec2=['sox','-e', 'signed', '-c', '1', '-b', '16', '-r', '20800', '-t','raw','s15', 'static/demo15.wav']
    subprocess.call(rec2)
So, I record the signal in the file 's15' and after I create a file .wav  using SOX.
Next, I want to stop rtl_fm command and I use stop_thread(), because I need to record different tracks for different frecuencies at the specified times. For that, I have to do it automatic  and that rtl_fm command runs or stops at this specified time.
My project consists on the reception of satellite signals. I have to recive the data of three satellites, so I have to set the correct frequency when one of them will be passing on the ground station.
I have another question. Which OS have you used to run the app?  I have had problem with rtl_fm on Linux x32, because the command doesn't finish neither (with crtl+C) when it is used directly in the terminal. Not happen that with Linux x64, but maybe it is not the reason.
Thank you very much.

**Comment by th0ma5w** [comment]
So I have tried it on 64-bit Windows (with Cygwin), 32-bit Linux, and 64-bit Linux... and I've also definitely had instances where I've had to force kill the process in another terminal window with the kill command, or kill it via the Task Manager in Windows, and I'm not entirely sure why.

I guess instead of what you have above, I would almost recommend not even using any code at all from this project here at all... 

According to https://stackoverflow.com/questions/13332268/python-subprocess-command-with-pipe you could do something like:

tune_cmd=['rtl_fm','-d','0','-M','wbfm','-f','99.5M','-g', '40','-p', '60', '-s','300000','s15']
rec_cmd=['sox','-e', 'signed', '-c', '1', '-b', '16', '-r', '20800', '-t','raw','s15', 'static/demo15.wav']
tuner = subprocess.Popen(tune_cmd, stdout=subprocess.pipe)
recorder = subprocess.Popen(rec_cmd, stdin=tuner.stdout)

Then (in theory, according to https://stackoverflow.com/questions/5033532/how-to-clean-up-after-subprocess-popen ) you could use tuner.kill() and recorder.kill() to stop?

**Comment by Jennifer92** [comment]
Thank you for your solution. It works, but I was interested in your funtion
'get_frequency', because I want to realise doppler correction. So, finally
I have used 'multiprocessing'  instead 'threading'. Thank you very much for
your ideas.
Kinds reagards.

2016-05-17 22:11 GMT+02:00 th0ma5w notifications@github.com:

**Comment by th0ma5w** [comment]
OH!!! That makes total sense I was thinking you'd have just static recordings. I'm glad multiprocessing works out. I hope to get into satellite stuff soon, so thanks for the inspiration. Let me know if you need anything else, and I'll try perhaps to get the threading stuff working better.
